<a href="https://colab.research.google.com/github/pavi-ninjaac/NuralNetwork_scratch/blob/main/FullyConnectedLayer/FullyConnectedLayer_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
#gonna train the XOR gate from scratch
import numpy as np

from keras.datasets import mnist
from keras.utils import to_categorical
from matplotlib import pyplot
import numpy as np

from keras.models import Sequential
from keras.layers import Dense,Flatten

In [2]:
class FClayer:
  def __init__(self , input_size , output_size):
    self.input = None
    self.output = None
    #rondomly initialize the weights
    self.weights = np.random.rand(input_size , output_size) - 0.5
    self.bias =  np.random.rand(1,output_size) - 0.5 

  def forward_propogation(self , input):
    self.input = input
    #print('weights',self.weights)
    #print('bias',self.bias)
    self.output = np.dot(self.input , self.weights) + self.bias
    return self.output

  def back_propogation(self , output_error , learning_rate):
    input_error = np.dot(output_error , self.weights.T)
    #print('back weight' , self.weights)
    weights_error = np.dot(self.input.T , output_error)
    bias_error = output_error
    #update the weights and bias
    self.weights -= learning_rate *  weights_error
    self.bias -= learning_rate * bias_error

    return input_error

In [21]:
#activation layer
#inherite the fully connected layer



class ActivationLayer(FClayer):
  def __init__(self, actvation , activation_derivated):
    self.actvation = actvation
    self.activation_derivated = activation_derivated

  def forward_propogation(self , input_data):
    self.input = input_data
    self.output = self.actvation(self.input)
    print('activation' , self.output)
    return self.output

  def back_propogation(self ,  output_error , learning_rate):
    return self.activation_derivated(self.input) * output_error

In [48]:
def tanh(x):
  return np.tanh(x)

def tanh_derivated(x):
  return 1-np.tanh(x) ** 2

#sigmoid
def sigmoid(x):
  return 1.0/(1+np.exp(-x))

def sigmoid_derivated(x):
  return sigmoid(x) * (1-sigmoid(x))


#rectifire linear unit
def relu(x):
  print(x)
  res = []
  for i in x:
    
    y = [max(0,a) for a in i]
    res.append(y)
  y = np.array(res)
  return y 

def relu_derivated(x):
  res = []
  for i in x:
    
    y = [1 if a> 0 else 0 for a in i]
    res.append(y)
  y = np.array(res)
  return y

#softmax
def softmax(x):
  return 

In [42]:
#defining the lose

def mse(y_true , y_pred):
  return np.mean(np.power(y_true - y_pred , 2))

def mse_derivated(y_true , y_pred):
  return 2*(y_pred - y_true) / y_true.size

In [54]:
#defning the network or model

class model:
  def __init__(self):
    self.layers = []
    self.loss = None
    self.loss_derivated = None

  #adding layer to the model
  def add(self , layer):
    self.layers.append(layer)

  def setloss(self, loss , loss_derivated):
    self.loss = loss
    self.loss_derivated = loss_derivated

  #predict the unknow data
  def predict(self , Newinput):
    samples = len(Newinput)
    result = []
    for i in range(samples):
      output = Newinput[i]
      
      for layer in self.layers:
        output = layer.forward_propogation(output)

      result.append(output)
    return result
  
  def fit(self , x_train , y_train , epoches , learning_rate):
    sampels = len(x_train)
    for i in range(epoches):
      err = 0
      for j in range(sampels):
        output = x_train[j]
        #print(output , j) 
        for layer in self.layers:
          print(layer)
          output = layer.forward_propogation(output)
          print(output)
        
        #compute the loss
        err += self.loss(y_train[j] , output)

        #backpropogation
        error = self.loss_derivated(y_train[j] , output)

        #update the weights
        for layer in reversed(self.layers):
          error = layer.back_propogation(error , learning_rate)
        
    #calculate the average error and display that
      err /= sampels
      print('epoches..'+str(i)+'/'+str(epoches)+'-------'+'Error',err)


In [50]:
#lets try with XOR operation to check it works fine
X_train = np.array([[[0,0]] , [[0,1]] , [[1,0]] , [[1,1]]])

y_train = np.array([[[0]] , [[1]] , [[1]] , [[0]]])


In [62]:
#binary classification
(Xtrain , ytrain) , (Xtest,ytest) = mnist.load_data()
#generating the binary dataset
X_train , y_train ,X_test , y_test = [],[],[],[]
for i in range(6000):
  if ytrain[i] == 0 or ytrain[i] == 1:
    X_train.append(Xtrain[i])
    y_train.append(ytrain[i])
for i in range(1000):
  if ytest[i] == 0 or ytest[i] == 1:
    X_test.append(Xtest[i])
    y_test.append(ytest[i])
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

#preprocessing
X_train = X_train.reshape(X_train.shape[0], 784, 1)
X_test = X_test.reshape(X_test.shape[0], 784, 1)

y_train = to_categorical(y_train,num_classes=2)
y_test = to_categorical(y_test,num_classes=2)

#normalize
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

X_train = X_train/255.0
X_test = X_test/255.0

In [63]:
X_train.shape

(1263, 784, 1)

In [65]:
#build the network
m = model()
m.add(FClayer(784,100))
m.add(ActivationLayer(relu,relu_derivated))

m.add(FClayer(100,10))
m.add(ActivationLayer(sigmoid,sigmoid_derivated))

m.setloss(mse , mse_derivated)
m.fit(X_train , y_train , epoches = 2 , learning_rate = 0.1)



ValueError: ignored

In [9]:
y_pred = model.predict(X_train)
y_pred

[array([[0.26723028]]),
 array([[0.61908763]]),
 array([[0.575527]]),
 array([[0.65980984]])]

In [10]:
#almost correct more epoches will bring better than this

In [47]:
x = [[ 0.1482825  ,-0.0291078 , -0.42258004]]
res = []
for i in x:
  print(i)
  y = [1 if a> 0 else 0 for a in i]
  res.append(y)
y = np.array(res)
y

[0.1482825, -0.0291078, -0.42258004]


array([[1, 0, 0]])