<a href="https://colab.research.google.com/github/pavi-ninjaac/NuralNetwork_scratch/blob/main/CNN/ConvolutionalLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# conolutional layer
import numpy as np

In [ ]:
class con2D:
  def __init__(self):
    self.filter = None
    self.bias = None
    

  
  #forward propogaton
  def forward_propogation(self, image , filter , kernal_size, strides = (1,1) ):
    """Convolute the image with the filter and strids"""
    input_dim , _ , img_channel = image.shape #input dimensions
    f_channel = img_channel               #filter channel must match with the image channel
    no_filters = filter                   # number of filters
    f_dim , _ = kernal_size               # get the filter size
    s , _ = strides
    f_size = (no_filters , f_channel , f_dim , f_dim) # get the strides dimentions

    #initialize the filter
    """ Initalize the filter with the noraml distribution with the standard deviation inversely proportional the square root of the number of units"""
    sdv = 1.0 / np.sqrt(np.prod(f_size))
    self.filter = np.random.normal(loc = 0, scale = sdv, size = f_size)
    self.bias = np.zeros((no_filters , 1)) # each for the one filters 

    #calculate the output dimension, so according to that i can create the empty array to store value
    out_dim = ((input_dim - f_dim) / s) + 1

    #create the empty array with output dimetions
    self.output = np.zeros((no_filters , out_dim, out_dim )) #syntax np.zeros(channel , row , col)

    for curr_filter in range(no_filters): # for loop over the number of filters
      curr_y = out_y =0
      #move vertically over the image
      while curr_y + f_dim <= input_dim:
        curr_x , out_x = 0
        #move horizondally
        while curr_x + f_dim <= input_dim:
          """perform convolution operation on the image"""
          self.output[curr_filter , curr_y , curr_x] = np.sum(self.filter[curr_filter] * image[: , curr_y : curr_y + f_dim , curr_x : curr_x + f_dim]) + self.bias[curr_filter]

          curr_x += s
          out_x +=1
        curr_y += s
        out_y += 1
  
    return output

    def back_propogation(self):
      pass



In [ ]:
class MaxPooling2D:
  def __init__(self , pool_size = 1, strides=None):
    self.pool_size = pool_size #getting the kernal size for pooling the layer out
    self.strides = strides
    pass
  def forward_propogation(self , image):

    """ downsample of the image using the kernal size and strides"""
    h_prev , w_prev , img_channel = image.shape    # shape of the image
    # calculate output dimensions after the maxpooling operation.
    h = int((h_prev - self.pool_size)/self.strides)+1 
    w = int((w_prev - self.pool_size)/self.strides)+1
    
    # create a matrix to hold the values of the maxpooling operation.
    self.output = np.zeros((n_c, h, w))
    # slide the window over every part of the image using stride s. Take the maximum value at each step.
    for i in range(n_c):
        curr_y = out_y = 0
        # slide the max pooling window vertically across the image
        while curr_y + f <= h_prev:
            curr_x = out_x = 0
            # slide the max pooling window horizontally across the image
            while curr_x + f <= w_prev:
                # choose the maximum value within the window at each step and store it to the output matrix
                self.output[i, out_y, out_x] = np.max(image[i, curr_y:curr_y+f, curr_x:curr_x+f])
                curr_x += s
                out_x += 1
            curr_y += s
            out_y += 1
    return self.output


In [ ]:
f_size = (2,3,3)
sdv = 1.0 / np.sqrt(np.prod(f_size))
sd = np.random.normal(loc = 0, scale = sdv, size = f_size)
sd

array([[[-0.2358713 ,  0.26419976, -0.05489258],
        [-0.07005125, -0.03529608, -0.13862036],
        [-0.42406881,  0.16785173, -0.26264137]],

       [[ 0.27956213,  0.14691208,  0.31053885],
        [-0.21537503,  0.16352159,  0.0658891 ],
        [-0.65043857,  0.19225158,  0.08999125]]])

In [ ]:
sd[:,0:1 , 0:1]

array([[[-0.2358713 ]],

       [[ 0.27956213]]])

In [ ]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])